/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursoemvideo;

/**
 *
 * @author Sgt Danilo
 */
public class CalculadoraAulaSete extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraAulaSete
     */
    public CalculadoraAulaSete() {
        initComponents();
        painelcalc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblresto2 = new javax.swing.JLabel();
        lblcubo = new javax.swing.JLabel();
        raiz = new javax.swing.JLabel();
        cubica = new javax.swing.JLabel();
        vabsoluto = new javax.swing.JLabel();
        lblresto = new javax.swing.JLabel();
        lblcubo2 = new javax.swing.JLabel();
        lblraiz = new javax.swing.JLabel();
        lblcubica = new javax.swing.JLabel();
        lblAbsoluto = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        jsValor = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelcalc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblresto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblcubo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        raiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cubica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vabsoluto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblresto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblcubo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblraiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblcubica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblAbsoluto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCalc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sgt Danilo\\Desktop\\sinais.png")); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        jsValor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jsValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Informe um valor:");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sgt Danilo\\Desktop\\calculadora.jpg")); // NOI18N

        jLabel2.setText("Teste");

        javax.swing.GroupLayout painelcalcLayout = new javax.swing.GroupLayout(painelcalc);
        painelcalc.setLayout(painelcalcLayout);
        painelcalcLayout.setHorizontalGroup(
            painelcalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcalcLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        painelcalcLayout.setVerticalGroup(
            painelcalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcalcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cubica)
                            .addComponent(raiz)
                            .addComponent(lblresto2)
                            .addComponent(vabsoluto)
                            .addComponent(lblcubo2))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAbsoluto)
                            .addComponent(lblresto)
                            .addComponent(lblraiz)
                            .addComponent(lblcubica)
                            .addComponent(lblcubo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jsValor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnCalc)))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelcalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jsValor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(raiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cubica))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblresto2)
                                    .addComponent(lblresto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcubo2)
                                    .addComponent(lblcubo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblraiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcubica)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vabsoluto)
                            .addComponent(lblAbsoluto))))
                .addGap(18, 18, 18)
                .addComponent(painelcalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int resto1,cubo,va;
        double valor,rq,rc;
        valor = Double.parseDouble(jsValor.getValue().toString());
        //valor = Double.parseDouble(txtValor.getText());
        resto1 = (int)valor%2;
        cubo = (int) Math.pow(valor,3);
        rq = Math.sqrt(valor);
        rc = Math.cbrt (valor);
        va = (int) Math.abs (valor);
        lblresto.setText(Integer.toString(resto1));
        lblcubo.setText(Integer.toString(cubo));
        lblraiz.setText(String.format("%.2f",rq));
        lblcubica.setText(String.format("%.2f",rc));
        lblAbsoluto.setText(Integer.toString(va));
        
        lblresto2.setText(" O resto da divisão por 2 é:");
        lblcubo2.setText(" O cubo é:");
        raiz.setText(" A raiz quadrada é:");
        cubica.setText(" A raiz cúbica é:");
        vabsoluto.setText(" O valor absoluto é:");
        
        painelcalc.setVisible(true);
        
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAulaSete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAulaSete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAulaSete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAulaSete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraAulaSete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel cubica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jsValor;
    private javax.swing.JLabel lblAbsoluto;
    private javax.swing.JLabel lblcubica;
    private javax.swing.JLabel lblcubo;
    private javax.swing.JLabel lblcubo2;
    private javax.swing.JLabel lblraiz;
    private javax.swing.JLabel lblresto;
    private javax.swing.JLabel lblresto2;
    private javax.swing.JPanel painelcalc;
    private javax.swing.JLabel raiz;
    private javax.swing.JLabel vabsoluto;
    // End of variables declaration//GEN-END:variables
}
