/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exe13;

import javax.swing.DefaultListModel;

/**
 *
 * @author Sgt Danilo
 */
public class TelaEx13 extends javax.swing.JFrame {

    /**
     * Creates new form TelaEx13
     */
    public TelaEx13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsIn = new javax.swing.JSlider();
        jsFim = new javax.swing.JSlider();
        jsPas = new javax.swing.JSlider();
        lblIn = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPas = new javax.swing.JLabel();
        txtRes = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Início");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Fim");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Passo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        jsIn.setMaximum(5);
        jsIn.setValue(0);
        jsIn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsInStateChanged(evt);
            }
        });
        getContentPane().add(jsIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 25, -1, -1));

        jsFim.setMaximum(20);
        jsFim.setMinimum(6);
        jsFim.setValue(6);
        jsFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsFimStateChanged(evt);
            }
        });
        getContentPane().add(jsFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 66, -1, -1));

        jsPas.setMaximum(10);
        jsPas.setMinimum(1);
        jsPas.setValue(1);
        jsPas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsPasStateChanged(evt);
            }
        });
        getContentPane().add(jsPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 104, -1, -1));

        lblIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIn.setText("0");
        getContentPane().add(lblIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblFim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFim.setText("0");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        lblPas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPas.setText("0");
        getContentPane().add(lblPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        txtRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResActionPerformed(evt);
            }
        });
        getContentPane().add(txtRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, 250));

        btnCalc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jScrollPane1.setViewportView(jLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 120, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsInStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsInStateChanged
        // TODO add your handling code here:
        lblIn.setText(Integer.toString(jsIn.getValue()));
    }//GEN-LAST:event_jsInStateChanged

    private void jsFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsFimStateChanged
        // TODO add your handling code here:
        lblFim.setText(Integer.toString(jsFim.getValue()));
    }//GEN-LAST:event_jsFimStateChanged

    private void jsPasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsPasStateChanged
        // TODO add your handling code here:
        lblPas.setText(Integer.toString(jsPas.getValue()));
    }//GEN-LAST:event_jsPasStateChanged

    private void txtResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int i = jsIn.getValue();
        int f = jsFim.getValue();
        int p = jsPas.getValue();
        int cc;
        String res = " ";
        DefaultListModel lista = new DefaultListModel();
        for(cc=i;cc<=f;cc+=p){
            lista.addElement(cc);            
            res +=  cc + "\n";
        }
        txtRes.setText(res);
        jLista.setModel(lista);
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEx13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEx13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEx13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEx13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEx13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jsFim;
    private javax.swing.JSlider jsIn;
    private javax.swing.JSlider jsPas;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblPas;
    private javax.swing.JTextField txtRes;
    // End of variables declaration//GEN-END:variables
}
